#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Colors!
source ~/.alias

PS1='\[\e[0;32m\][\u@\h \[\e[1;35m\]\W\[\e[0;32m\]]\$\[\e[0m\] '

# ------- CUSTOM BIN ---------
if [[ ! -d ~/bin ]]; then
    mkdir ~/bin
fi
export PATH="~/bin:$PATH"
# --- OS X HOMEBREW SETTINGS ---
#if [[ $(uname -s) == "Darwin" ]]; then
#    export PATH="/usr/local/bin:$PATH"
#fi
