#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Colors!
source ~/.bashcolors/base16-monokai.dark.sh

alias ls='ls --color=auto --group-directories-first'
#PS1='[\u@\h \W]\$ '
PS1='\[\e[0;31m\][\u@\h \W]\$\[\e[0m\] '

# ------- CUSTOM BIN ---------
if [[ ! -d ~/bin ]]; then
    mkdir ~/bin
fi
export PATH="$PATH:~/bin"
