set nocompatible
filetype off

" Vundle stuff
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'altercation/vim-colors-solarized'

" Language plugins
Plugin 'rust-lang/rust.vim'
Plugin 'vim-scripts/VimClojure'
Plugin 'tfnico/vim-gradle'

call vundle#end()
filetype plugin indent on

" Nice defaults
syntax on
set encoding=utf-8
set number
set showcmd
set ruler
set backspace=2

" Colorscheme for now
set background=dark
colorscheme hybrid

" Airline stuff
set laststatus=2
let g:airline_powerline_fonts=1
let g:airline_theme="dark"

" Editor settings
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set smarttab

