set nocompatible
filetype off

" Vundle stuff
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'bling/vim-airline'
Plugin 'christoomey/vim-tmux-navigator'

" Language plugins
Plugin 'helino/vim-nasm'
Plugin 'rust-lang/rust.vim'
Plugin 'vim-scripts/VimClojure'
Plugin 'tfnico/vim-gradle'

call vundle#end()
filetype plugin indent on

" Nice defaults
syntax on
set encoding=utf-8
set number
set showcmd
set ruler
set backspace=2

" Colorscheme for now
let s:uname = system("echo -n \"$(uname)\"")
if !v:shell_error && s:uname =="Darwin"
    " Do OSX things here
    colorscheme base16-monokai
elseif
    " TODO: What colorscheme do I want to roll with on Linux?
endif

" Airline stuff
set laststatus=2
let g:airline_powerline_fonts=1
let g:airline_theme="dark"

" Editor settings
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set smarttab
