set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Plugin 'bling/vim-airline'
Plugin 'helino/vim-nasm'

call vundle#end()
filetype plugin indent on

syntax on
set encoding=utf-8
set number
set showcmd
set ruler
set backspace=2
colorscheme base16-monokai

" For vim-airline
" let g:airline_powerline_fonts = 1

" Learning vimscript yo
