# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Themes in: ~/.oh-my-zsh/themes/
ZSH_THEME="gentoo"

# oh_my_zsh options
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# Make the above settings take place
source $ZSH/oh-my-zsh.sh
# User configuration
# editor settings
export EDITOR='vim'
export VISUAL='vim'

# Use vim keybindings to edit the command line
bindkey -v
bindkey '^R' history-incremental-search-backward

# Homebrew settings
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_CASK_OPTS='--appdir=/Applications'

# PATH things
export PATH="/usr/sbin:/sbin:/usr/local/bin:/bin:~/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
export MANPATH="/usr/local/man:$MANPATH"

# Load custom aliases
source ~/.alias

# Set locale
export LANG=en_US.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# OPAM configuration
. /Users/xiaobai/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
